/**
 * Maps an ISO 4217 currency code to its primary country/region name.
 *
 * Used to auto-suggest a country when a currency is selected in the rate group
 * modal. For currencies shared by many countries (EUR, XAF, XOF, XCD, XPF) the
 * broad region name is used. The value is a starting suggestion the user can
 * always override.
 */
export const CURRENCY_COUNTRY: Record<string, string> = {
  AED: 'United Arab Emirates',
  AFN: 'Afghanistan',
  ALL: 'Albania',
  AMD: 'Armenia',
  ANG: 'Netherlands Antilles',
  AOA: 'Angola',
  ARS: 'Argentina',
  AUD: 'Australia',
  AWG: 'Aruba',
  AZN: 'Azerbaijan',
  BAM: 'Bosnia and Herzegovina',
  BBD: 'Barbados',
  BDT: 'Bangladesh',
  BGN: 'Bulgaria',
  BHD: 'Bahrain',
  BIF: 'Burundi',
  BMD: 'Bermuda',
  BND: 'Brunei',
  BOB: 'Bolivia',
  BRL: 'Brazil',
  BSD: 'Bahamas',
  BTN: 'Bhutan',
  BWP: 'Botswana',
  BYN: 'Belarus',
  BZD: 'Belize',
  CAD: 'Canada',
  CDF: 'DR Congo',
  CHF: 'Switzerland',
  CLP: 'Chile',
  CNY: 'China',
  COP: 'Colombia',
  CRC: 'Costa Rica',
  CUP: 'Cuba',
  CVE: 'Cape Verde',
  CZK: 'Czechia',
  DJF: 'Djibouti',
  DKK: 'Denmark',
  DOP: 'Dominican Republic',
  DZD: 'Algeria',
  EGP: 'Egypt',
  ERN: 'Eritrea',
  ETB: 'Ethiopia',
  EUR: 'Eurozone',
  FJD: 'Fiji',
  FKP: 'Falkland Islands',
  GBP: 'United Kingdom',
  GEL: 'Georgia',
  GHS: 'Ghana',
  GIP: 'Gibraltar',
  GMD: 'Gambia',
  GNF: 'Guinea',
  GTQ: 'Guatemala',
  GYD: 'Guyana',
  HKD: 'Hong Kong',
  HNL: 'Honduras',
  HRK: 'Croatia',
  HTG: 'Haiti',
  HUF: 'Hungary',
  IDR: 'Indonesia',
  ILS: 'Israel',
  INR: 'India',
  IQD: 'Iraq',
  IRR: 'Iran',
  ISK: 'Iceland',
  JMD: 'Jamaica',
  JOD: 'Jordan',
  JPY: 'Japan',
  KES: 'Kenya',
  KGS: 'Kyrgyzstan',
  KHR: 'Cambodia',
  KMF: 'Comoros',
  KPW: 'North Korea',
  KRW: 'South Korea',
  KWD: 'Kuwait',
  KYD: 'Cayman Islands',
  KZT: 'Kazakhstan',
  LAK: 'Laos',
  LBP: 'Lebanon',
  LKR: 'Sri Lanka',
  LRD: 'Liberia',
  LSL: 'Lesotho',
  LYD: 'Libya',
  MAD: 'Morocco',
  MDL: 'Moldova',
  MGA: 'Madagascar',
  MKD: 'North Macedonia',
  MMK: 'Myanmar',
  MNT: 'Mongolia',
  MOP: 'Macau',
  MRU: 'Mauritania',
  MUR: 'Mauritius',
  MVR: 'Maldives',
  MWK: 'Malawi',
  MXN: 'Mexico',
  MYR: 'Malaysia',
  MZN: 'Mozambique',
  NAD: 'Namibia',
  NGN: 'Nigeria',
  NIO: 'Nicaragua',
  NOK: 'Norway',
  NPR: 'Nepal',
  NZD: 'New Zealand',
  OMR: 'Oman',
  PAB: 'Panama',
  PEN: 'Peru',
  PGK: 'Papua New Guinea',
  PHP: 'Philippines',
  PKR: 'Pakistan',
  PLN: 'Poland',
  PYG: 'Paraguay',
  QAR: 'Qatar',
  RON: 'Romania',
  RSD: 'Serbia',
  RUB: 'Russia',
  RWF: 'Rwanda',
  SAR: 'Saudi Arabia',
  SBD: 'Solomon Islands',
  SCR: 'Seychelles',
  SDG: 'Sudan',
  SEK: 'Sweden',
  SGD: 'Singapore',
  SHP: 'Saint Helena',
  SLL: 'Sierra Leone',
  SOS: 'Somalia',
  SRD: 'Suriname',
  SSP: 'South Sudan',
  STN: 'São Tomé and Príncipe',
  SVC: 'El Salvador',
  SYP: 'Syria',
  SZL: 'Eswatini',
  THB: 'Thailand',
  TJS: 'Tajikistan',
  TMT: 'Turkmenistan',
  TND: 'Tunisia',
  TOP: 'Tonga',
  TRY: 'Turkey',
  TTD: 'Trinidad and Tobago',
  TWD: 'Taiwan',
  TZS: 'Tanzania',
  UAH: 'Ukraine',
  UGX: 'Uganda',
  USD: 'United States',
  UYU: 'Uruguay',
  UZS: 'Uzbekistan',
  VES: 'Venezuela',
  VND: 'Vietnam',
  VUV: 'Vanuatu',
  WST: 'Samoa',
  XAF: 'Central Africa (CFA)',
  XCD: 'East Caribbean',
  XOF: 'West Africa (CFA)',
  XPF: 'French Pacific',
  YER: 'Yemen',
  ZAR: 'South Africa',
  ZMW: 'Zambia',
  ZWL: 'Zimbabwe',
};

/** Returns the suggested country for a currency code, or undefined. */
export function countryForCurrency(currency: string | undefined | null): string | undefined {
  if (!currency) return undefined;
  return CURRENCY_COUNTRY[currency.trim().toUpperCase()];
}
